language: go

go:
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"
  - master

dist:
  - xenial


before_script:
  - go get "github.com/BurntSushi/toml"
  - go get "github.com/gorilla/mux"
  - go get "github.com/mattn/go-sqlite3"
  - go get "github.com/eclipse/paho.mqtt.golang"
  - go get "github.com/jacobsa/go-serial/serial"

script:
  - make
  - make test
