language: go

go:
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"
  - master

dist:
  - xenial


before_script:
  - go get "github.com/BurntSushi/toml"
  - go get "github.com/go-sql-driver/mysql"
  - go get "github.com/gorilla/mux"
