DefaultRemote = "meteo"           # Default server if nothing is given


[Remotes.meteo]
Remote = "https://localhost/meteo"

# Declare ranges for individual station (for color output)
[Ranges.meteo]
# Temperature range [ err_low, warn_low, warn_high, err_high ]
# Ranges must be float (e.g. 1.0 instead of 1)
temp_range = [ 10.0, 22.0, 30.0, 40.0 ]
hum_range = [ 10.0, 10.0, 50.0, 80.0 ]
